In [1]:
import os
import keras 
!pip install seaborn
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout, BatchNormalization
from PIL import Image
import numpy as np
import seaborn as sns

import pandas as pd
import matplotlib.pyplot as plt
plt.style.use('dark_background')
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder 

You should consider upgrading via the 'C:\Users\Shreeyash Pandey\uh\envs\new\python.exe -m pip install --upgrade pip' command.


In [2]:
encoder = OneHotEncoder()
encoder.fit([[0], [1]]) 

OneHotEncoder()

In [3]:
data = []
paths = []
result = []

for r, d, f in os.walk(r'C:\Users\Shreeyash Pandey\Downloads\archive (3)\DataSet\yes'):
    for file in f:
        if '.jpg' in file:
            paths.append(os.path.join(r, file))

for path in paths:
    img = Image.open(path)
    img = img.resize((128,128))
    img = np.array(img)
    if(img.shape == (128,128,3)):
        data.append(np.array(img))
        result.append(encoder.transform([[0]]).toarray())

In [4]:
paths = []
for r, d, f in os.walk(r"C:\Users\Shreeyash Pandey\Downloads\archive (3)\DataSet\no"):
    for file in f:
        if '.jpg' in file:
            paths.append(os.path.join(r, file))

for path in paths:
    img = Image.open(path)
    img = img.resize((128,128))
    img = np.array(img)
    if(img.shape == (128,128,3)):
        data.append(np.array(img))
        result.append(encoder.transform([[1]]).toarray())

In [5]:
data = np.array(data)
data.shape

(2594, 128, 128, 3)

In [6]:
result = np.array(result)
result = result.reshape(2594,2)

In [7]:
x_train,x_test,y_train,y_test = train_test_split(data, result, test_size=0.2, shuffle=True, random_state=0)

In [8]:
from keras.applications.inception_v3 import InceptionV3
from keras.applications.inception_v3 import preprocess_input
from keras.applications.inception_v3 import decode_predictions

In [9]:
model = InceptionV3(input_shape=(128,128,3),weights='imagenet', include_top=False)


In [10]:
from tensorflow.keras.preprocessing import image
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D

In [11]:
base_model = InceptionV3(weights='imagenet', include_top=False)

x = base_model.output
x = GlobalAveragePooling2D()(x)
# let's add a fully-connected layer

x = Dense(1024, activation='relu')(x)


predictions = Dense(2, activation='sigmoid')(x)

# this is the model we will train
model = Model(inputs=base_model.input, outputs=predictions)

# first: train only the top layers (which were randomly initialized)
# i.e. freeze all convolutional InceptionV3 layers
for layer in base_model.layers:
    layer.trainable = False

# compile the model (should be done *after* setting layers to non-trainable)
model.compile(optimizer='rmsprop', loss='categorical_crossentropy',metrics=['accuracy'])

In [12]:
x_train

array([[[[  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0],
         ...,
         [  5,   5,   5],
         [ 13,  13,  13],
         [ 11,  11,  11]],

        [[  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0],
         ...,
         [  6,   6,   6],
         [  8,   8,   8],
         [  6,   6,   6]],

        [[  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0],
         ...,
         [ 15,  15,  15],
         [ 10,  10,  10],
         [ 11,  11,  11]],

        ...,

        [[  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0],
         ...,
         [  9,   9,   9],
         [ 19,  19,  19],
         [ 18,  18,  18]],

        [[  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0],
         ...,
         [ 10,  10,  10],
         [ 12,  12,  12],
         [ 10,  10,  10]],

        [[  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0],
         ...,
         [  9,   9,   9],
        

In [13]:
history = model.fit(x_train, y_train, epochs = 5, batch_size = 50, verbose = 1,validation_data = (x_test, y_test))

Epoch 1/5
42/42 [==============================] - 106s 2s/step - loss: 61.1260 - accuracy: 0.5851 - val_loss: 4.6350 - val_accuracy: 0.7225
Epoch 2/5
42/42 [==============================] - 88s 2s/step - loss: 6.8732 - accuracy: 0.6752 - val_loss: 4.2943 - val_accuracy: 0.6879
Epoch 3/5
42/42 [==============================] - 71s 2s/step - loss: 3.8292 - accuracy: 0.7176 - val_loss: 1.5065 - val_accuracy: 0.7746
Epoch 4/5
42/42 [==============================] - 57s 1s/step - loss: 2.3592 - accuracy: 0.7205 - val_loss: 0.8033 - val_accuracy: 0.8015
Epoch 5/5
42/42 [==============================] - 70s 2s/step - loss: 1.5603 - accuracy: 0.7422 - val_loss: 3.5869 - val_accuracy: 0.5780


In [14]:
accur=model.evaluate(x_test,y_test)

17/17 [==============================] - 15s 826ms/step - loss: 3.5869 - accuracy: 0.5780


In [15]:
import cv2 

In [16]:
img = cv2.imread(r"C:\Users\Shreeyash Pandey\Downloads\archive (3)\TestDataSet\yes\y22.jpg", cv2.IMREAD_COLOR)

In [18]:
img=np.resize(img,(128,128))

In [19]:
img.shape

(128, 128)

In [20]:
img=np.array(img)

In [21]:
img.shape

(128, 128)

In [22]:
img.reshape(128,128,1)

array([[[0],
        [0],
        [0],
        ...,
        [0],
        [0],
        [0]],

       [[0],
        [0],
        [0],
        ...,
        [0],
        [0],
        [0]],

       [[0],
        [0],
        [0],
        ...,
        [0],
        [0],
        [0]],

       ...,

       [[0],
        [0],
        [0],
        ...,
        [0],
        [0],
        [0]],

       [[0],
        [0],
        [0],
        ...,
        [0],
        [0],
        [0]],

       [[0],
        [0],
        [0],
        ...,
        [0],
        [0],
        [0]]], dtype=uint8)

In [23]:
img = image.load_img(r"C:\Users\Shreeyash Pandey\Desktop\Brain Tumor detection\static\uploads\y21.jpg", target_size=(128, 128))
img = np.expand_dims(img, axis=0)
result=model.predict(img)
print(result)

[[0.43168646 0.9997118 ]]


In [24]:
np.argmax(result,axis=1)


array([1], dtype=int64)

In [25]:
model.save("model")

INFO:tensorflow:Assets written to: model\assets


In [1]:
import os
import urllib.request
from flask import Flask, flash, request, redirect, url_for, render_template
from werkzeug.utils import secure_filename
import numpy as np
import tensorflow as tf

ASSET_FOLDER = 'static/assets/'

app = Flask(__name__)
app.config['ASSET_FOLDER'] = ASSET_FOLDER

github_icon = os.path.join(app.config['ASSET_FOLDER'], r'C:\Users\Shreeyash Pandey\Documents\GitHub\Brain-Tumor-Detection-Using-Inception-V3\static\assets\github.png')
linkedin_icon = os.path.join(app.config['ASSET_FOLDER'], r'C:\Users\Shreeyash Pandey\Documents\GitHub\Brain-Tumor-Detection-Using-Inception-V3\static\assets\linkedin.png')
instagram_icon = os.path.join(app.config['ASSET_FOLDER'], r'C:\Users\Shreeyash Pandey\Documents\GitHub\Brain-Tumor-Detection-Using-Inception-V3\static\assets\instagram.png')
twitter_icon = os.path.join(app.config['ASSET_FOLDER'], r'C:\Users\Shreeyash Pandey\Documents\GitHub\Brain-Tumor-Detection-Using-Inception-V3\static\assets\twitter.png')
bg_video = os.path.join(app.config['ASSET_FOLDER'], r'C:\Users\Shreeyash Pandey\Documents\GitHub\Brain-Tumor-Detection-Using-Inception-V3\static\assets\bg_vedio.mp4')
    
@app.route('/')
def upload_form():
    return render_template('index.html', type="", githubicon=github_icon, linkedinicon=linkedin_icon, instagramicon=instagram_icon, twittericon=twitter_icon, bgvideo=bg_video)

@app.route('/', methods=['POST'])
def upload_image():
    file = request.files['file']
    print(file.filename)
    file.save(os.path.join("static/uploads", secure_filename(file.filename)))

    imvar = tf.keras.preprocessing.image.load_img(os.path.join("static/uploads", secure_filename(file.filename))).resize((128, 128))
    imarr = tf.keras.preprocessing.image.img_to_array(imvar)
    imarr = np.array([imarr])
    model2 = tf.keras.models.load_model("model")
    impred = model2.predict(imarr)

    def roundoff(arr):
        """To round off according to the argmax of each predicted label array. """
        arr[np.argwhere(arr != arr.max())] = 0
        arr[np.argwhere(arr == arr.max())] = 1
        return arr

    for classpreds in impred:
        impred = roundoff(classpreds)
    
    classcount = 1
    for count in range(2):
        if impred[count] == 1.0:
            break
        else:
            classcount=2
    
    classdict = {1: "Brain Tumor Exist", 2: "NO Brain Tumor"}
    print(classdict[classcount])

    c = 'xyz'
    return render_template('index.html', type="Patient is suffering from "+str(classdict[classcount]), githubicon=github_icon, linkedinicon=linkedin_icon, instagramicon=instagram_icon, twittericon=twitter_icon, bgvideo=bg_video)

if __name__ == "__main__":
    app.run()

 * Serving Flask app '__main__' (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [12/Aug/2022 03:18:48] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [12/Aug/2022 03:18:48] "GET /github.png HTTP/1.1" 404 -
127.0.0.1 - - [12/Aug/2022 03:18:48] "GET /linkedin.png HTTP/1.1" 404 -
127.0.0.1 - - [12/Aug/2022 03:18:49] "GET /twitter.png HTTP/1.1" 404 -
127.0.0.1 - - [12/Aug/2022 03:18:49] "GET /instagram.png HTTP/1.1" 404 -
127.0.0.1 - - [12/Aug/2022 03:18:49] "GET /bg_vedio.mp4 HTTP/1.1" 404 -


y21.jpg


127.0.0.1 - - [12/Aug/2022 03:22:11] "POST / HTTP/1.1" 200 -
127.0.0.1 - - [12/Aug/2022 03:22:11] "

NO Brain Tumor


GET /github.png HTTP/1.1" 404 -
127.0.0.1 - - [12/Aug/2022 03:22:11] "GET /linkedin.png HTTP/1.1" 404 -
127.0.0.1 - - [12/Aug/2022 03:22:12] "GET /twitter.png HTTP/1.1" 404 -
127.0.0.1 - - [12/Aug/2022 03:22:12] "GET /instagram.png HTTP/1.1" 404 -
127.0.0.1 - - [12/Aug/2022 03:22:21] "GET /bg_vedio.mp4 HTTP/1.1" 404 -
