In [3]:
import os
import keras 
!pip install seaborn
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout, BatchNormalization
from PIL import Image
import numpy as np
import seaborn as sns

import pandas as pd
import matplotlib.pyplot as plt
plt.style.use('dark_background')
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder 

In [4]:
encoder = OneHotEncoder()
encoder.fit([[0], [1]]) 

OneHotEncoder()

In [5]:
data = []
paths = []
result = []

for r, d, f in os.walk(r'C:\Users\Shreeyash Pandey\Downloads\archive (3)\DataSet\yes'):
    for file in f:
        if '.jpg' in file:
            paths.append(os.path.join(r, file))

for path in paths:
    img = Image.open(path)
    img = img.resize((128,128))
    img = np.array(img)
    if(img.shape == (128,128,3)):
        data.append(np.array(img))
        result.append(encoder.transform([[0]]).toarray())

In [6]:
paths = []
for r, d, f in os.walk(r"C:\Users\Shreeyash Pandey\Downloads\archive (3)\DataSet\no"):
    for file in f:
        if '.jpg' in file:
            paths.append(os.path.join(r, file))

for path in paths:
    img = Image.open(path)
    img = img.resize((128,128))
    img = np.array(img)
    if(img.shape == (128,128,3)):
        data.append(np.array(img))
        result.append(encoder.transform([[1]]).toarray())

In [7]:
data = np.array(data)
data.shape

(2594, 128, 128, 3)

In [8]:
result = np.array(result)
result = result.reshape(2594,2)

In [9]:
x_train,x_test,y_train,y_test = train_test_split(data, result, test_size=0.2, shuffle=True, random_state=0)

In [10]:
from keras.applications.inception_v3 import InceptionV3
from keras.applications.inception_v3 import preprocess_input
from keras.applications.inception_v3 import decode_predictions

In [11]:
model = InceptionV3(input_shape=(128,128,3),weights='imagenet', include_top=False)


In [12]:
from tensorflow.keras.preprocessing import image
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D

In [13]:
base_model = InceptionV3(weights='imagenet', include_top=False)

x = base_model.output
x = GlobalAveragePooling2D()(x)
# let's add a fully-connected layer

x = Dense(1024, activation='relu')(x)


predictions = Dense(2, activation='sigmoid')(x)

# this is the model we will train
model = Model(inputs=base_model.input, outputs=predictions)

# first: train only the top layers (which were randomly initialized)
# i.e. freeze all convolutional InceptionV3 layers
for layer in base_model.layers:
    layer.trainable = False

# compile the model (should be done *after* setting layers to non-trainable)
model.compile(optimizer='rmsprop', loss='categorical_crossentropy',metrics=['accuracy'])

In [14]:
x_train

array([[[[  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0],
         ...,
         [  5,   5,   5],
         [ 13,  13,  13],
         [ 11,  11,  11]],

        [[  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0],
         ...,
         [  6,   6,   6],
         [  8,   8,   8],
         [  6,   6,   6]],

        [[  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0],
         ...,
         [ 15,  15,  15],
         [ 10,  10,  10],
         [ 11,  11,  11]],

        ...,

        [[  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0],
         ...,
         [  9,   9,   9],
         [ 19,  19,  19],
         [ 18,  18,  18]],

        [[  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0],
         ...,
         [ 10,  10,  10],
         [ 12,  12,  12],
         [ 10,  10,  10]],

        [[  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0],
         ...,
         [  9,   9,   9],
        

In [18]:
history = model.fit(x_train, y_train, epochs = 50, batch_size = 10, verbose = 1,validation_data = (x_test, y_test))

Epoch 1/50
208/208 [==============================] - 61s 295ms/step - loss: 0.4325 - accuracy: 0.9214 - val_loss: 0.4560 - val_accuracy: 0.9133
Epoch 2/50
208/208 [==============================] - 62s 298ms/step - loss: 0.4846 - accuracy: 0.9176 - val_loss: 0.8440 - val_accuracy: 0.8709
Epoch 3/50
208/208 [==============================] - 71s 342ms/step - loss: 0.4750 - accuracy: 0.9258 - val_loss: 2.0432 - val_accuracy: 0.8189
Epoch 4/50
208/208 [==============================] - 75s 363ms/step - loss: 0.4693 - accuracy: 0.9258 - val_loss: 1.4807 - val_accuracy: 0.8189
Epoch 5/50
208/208 [==============================] - 65s 310ms/step - loss: 0.5697 - accuracy: 0.9253 - val_loss: 1.0420 - val_accuracy: 0.8805
Epoch 6/50
208/208 [==============================] - 65s 314ms/step - loss: 0.4371 - accuracy: 0.9378 - val_loss: 0.5085 - val_accuracy: 0.9171
Epoch 7/50
208/208 [==============================] - 63s 305ms/step - loss: 0.3453 - accuracy: 0.9494 - val_loss: 0.8286 - val_ac

In [19]:
accur=model.evaluate(x_test,y_test)

17/17 [==============================] - 9s 530ms/step - loss: 1.5024 - accuracy: 0.9345


In [20]:
import cv2 

In [24]:
img = cv2.imread(r"C:\Users\Shreeyash Pandey\Downloads\archive (3)\TestDataSet\yes\y22.jpg", cv2.IMREAD_COLOR)

In [28]:
img.resize(128,128)

In [30]:
img.shape

(128, 128)

In [31]:
img=np.array(img)

In [32]:
img.shape

(128, 128)

In [33]:
img.reshape(128,128,1)

array([[[0],
        [0],
        [0],
        ...,
        [0],
        [0],
        [0]],

       [[0],
        [0],
        [0],
        ...,
        [0],
        [0],
        [0]],

       [[0],
        [0],
        [0],
        ...,
        [0],
        [0],
        [0]],

       ...,

       [[0],
        [0],
        [0],
        ...,
        [0],
        [0],
        [0]],

       [[0],
        [0],
        [0],
        ...,
        [0],
        [0],
        [0]],

       [[0],
        [0],
        [0],
        ...,
        [0],
        [0],
        [0]]], dtype=uint8)

In [48]:
img = image.load_img(r"", target_size=(128, 128))
img = np.expand_dims(img, axis=0)
result=model.predict(img)
print(result)

[[6.5880755e-08 1.0000000e+00]]


In [49]:
np.argmax(result,axis=1)

array([1], dtype=int64)